apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: nova
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2022-05-05T23:19:28Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/managed-by: Helm
  name: nova-svc
  namespace: nova-ns
  resourceVersion: "1804992"
  uid: d95405e2-bbfc-4e97-af58-66540135fe26
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.138.162
  clusterIPs:
  - 10.100.138.162
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: port443
    nodePort: 32297
    port: 443
    protocol: TCP
    targetPort: 443
  - name: port80
    nodePort: 32643
    port: 80
    protocol: TCP
    targetPort: 80
  - name: novac
    nodePort: 31318
    port: 1080
    protocol: TCP
    targetPort: 1080
  selector:
    app: nova-nvc
    deployment: nova-dpl
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: ad95405e2bbfc4e97af5866540135fe2-1347037189.us-west-2.elb.amazonaws.com
