apiVersion: v1
kind: Service
metadata:
  name: test-nova-svc
  namespace: nova-ns
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nova-nvc
    deployment: nova-dpl